language: java
jdk:
  - openjdk8
before_install:
  - "echo skipped"
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip
script:
  - "echo skipped"
after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - mynameisfhb@gmail.com